spring:
  thymeleaf:
    cache: false
  docker:
    compose:
      file: ./dev-compose.yaml
  cloud:
    aws:
      region:
        static: ap-northeast-1
      credentials:
        access-key: test
        secret-key: test
      s3:
        endpoint: http://localhost:4566
        path-style-access-enabled: true
